### ISSUE TITLE
make run_dev gives errors on IOS

### ISSUE THREAD

**Issue by yakupbaser** [ntminhdn/Flutter-Bloc-CleanArchitecture#1]
Edit//
İt works like a charm. 
It was a certificate provisioning error.

**Comment by yakupbaser** [comment]
Everything is perfect on the android side but i think there are some config problems in build phases on ios. i can run the app on ios emulator but i cant create ipa file. Apple signature settings seem correct on my side. Can you try to get build on ios?

**Comment by ntminhdn** [comment]
@yakupbaser I think it is related to architecture configs. You could try to change `Architectures` config to `Standard Architectures $(ARCHS_STANDARD)` and remove all configs of `Excluded Architectures` like this.

Make sure you changed `bundle_id` in `Develop.xcconfig`

<img width="1109" alt="Screen Shot 2023-01-20 at 21 59 44" src="https://user-images.githubusercontent.com/22645452/213730426-0b2dc1f3-cca9-4e4f-b353-1e87a487db3c.png">

**Comment by yakupbaser** [comment]
I did what you said but the problem was not fixed.

**Comment by ntminhdn** [comment]
@yakupbaser Could you push your example? I will review it.

**Comment by yakupbaser** [comment]
I pulled the last commit and got a build when I tried again with Flutter 3.7.2. It's successful. Closed.
