### ISSUE TITLE
Bloc test

### ISSUE THREAD

**Issue by bedirhanayydin** [ntminhdn/Flutter-Bloc-CleanArchitecture#10]
Hi, can you add a bloc test example for the Login page?

**Comment by bedirhanayydin** [comment]
Hata alıyorum; 
`LateInitializationError: Field '_commonBloc@2463329749' has not been initialized.`

**Comment by bedirhanayydin** [comment]
I am getting error; 
`LateInitializationError: Field '_commonBloc@2463329749' has not been initialized.`

**Comment by ntminhdn** [comment]
@bedirhanayydin Here you are: https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/pull/11

**Comment by bedirhanayydin** [comment]
I will try and get back to you. Thank you for your interest.

**Comment by bedirhanayydin** [comment]
It worked successfully. Thanks.
