### ISSUE TITLE
Error when run make sync

### ISSUE THREAD

**Issue by tranhoang123** [ntminhdn/Flutter-Bloc-CleanArchitecture#13]
melos exec
  └> flutter packages pub run build_runner build --delete-conflicting-outputs
     └> FAILED (in 4 packages)
        └> shared (with exit code 78)
        └> data (with exit code 78)
        └> domain (with exit code 78)
        └> app (with exit code 78)
I met this error when "make sync" generate file. 

So I try to run in a package "flutter packages pub run build_runner build --delete-conflicting-outputs"
[INFO] Generating build script...
[INFO] Generating build script completed, took 729ms

[INFO] Precompiling build script......
[WARNING] ../../../flutter/.pub-cache/hosted/pub.dartlang.org/source_gen-1.2.7/lib/src/library.dart:166:70: Error: A value of type 'List<ClassElement>' can't be returned from a function with return type 'Iterable<EnumElement>'.
 - 'List' is from 'dart:core'.
 - 'ClassElement' is from 'package:analyzer/dart/element/element.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-4.7.0/lib/dart/element/element.dart').
 - 'Iterable' is from 'dart:core'.
 - 'EnumElement' is from 'package:analyzer/dart/element/element.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-4.7.0/lib/dart/element/element.dart').
  Iterable<EnumElement> get enums => element.units.expand((cu) => cu.enums);
                                                                     ^
[INFO] Precompiling build script... completed, took 1.4s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

My "flutter doctor -v" 
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-x64, locale en-VN)
    • Flutter version 3.3.9 on channel stable at /Users/tranhoang/Desktop/project/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/tranhoang/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • ANDROID_HOME = /Users/tranhoang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • 2AD12D89-5BE0-4B5A-B9DB-F1B3625BFEAC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ntminhdn** [comment]
@tranhoang123 It seems to be caused by a version conflict. I upgraded the Flutter version to the latest (3.7.1) so please update and then recheck it. If you got any other errors, please try to run `make pub_upgrade` and `pod install` to upgrade pubs and reinstall pods.
