### ISSUE TITLE
Not able to update app version

### ISSUE THREAD

**Issue by harshmittal2810** [ntminhdn/Flutter-Bloc-CleanArchitecture#18]
I am trying to update app version in app/pubspec.yaml file but android/ios both are only showing default versions.
Is there any script or way to change app version easily
Also is there any way to update package name through script, please guide me. 

<img width="345" alt="Screenshot 2023-02-28 at 6 56 20 PM" src="https://user-images.githubusercontent.com/10369985/221867469-0b82a852-6ac1-41e6-b002-16e370138cee.png">

<img width="680" alt="Screenshot 2023-02-28 at 6 55 15 PM" src="https://user-images.githubusercontent.com/10369985/221867525-3ac6639a-0f9e-4d77-a3ef-20c93123ebec.png">

**Comment by ntminhdn** [comment]
@harshmittal2810  To update the version name and version code or build number. Please update configs in files:
* iOS: `Develop.xcconfig`, `Staging.xcconfig`, `Qa.xcconfig`, `Production.xcconfig`: https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/blob/master/app/ios/Flutter/Develop.xcconfig

![image](https://user-images.githubusercontent.com/22645452/221869137-b16345e8-0898-49b3-9e1d-2f8ef53bf8f6.png)

* Android: https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/blob/master/app/android/app/build.gradle

![image](https://user-images.githubusercontent.com/22645452/221868248-77924271-f85f-4647-93f3-5331f866dc66.png)
