### ISSUE TITLE
Flutter 3.10.4

### ISSUE THREAD

**Issue by bedirhanayydin** [ntminhdn/Flutter-Bloc-CleanArchitecture#19]
**Hello.** Will you update the project according to the current flutter version?

**Comment by rasflp** [comment]
It would be great! This is a pretty handy starting point for a clean architecture with Flutter.

**Comment by yakupbaser** [comment]
Hi, that would be great! Thanks.

**Comment by mynavitechtus-minhnt3** [comment]
@bedirhanayydin I will update this project according to the current Flutter version this weekend

**Comment by bedirhanayydin** [comment]
I'm looking forward to it. Thanks

**Comment by mynavitechtus-minhnt3** [comment]
@bedirhanayydin I updated this project to Flutter 3.10.5. Check this [pull request](https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/pull/20) for more details.

**Comment by bedirhanayydin** [comment]
Thank you I will try it as soon as possible.
