### ISSUE TITLE
Flavor Reading Problem

### ISSUE THREAD

**Issue by bedirhanayydin** [ntminhdn/Flutter-Bloc-CleanArchitecture#2]
In the Qa environment, I runned the application in debug, but the app gives Flavor that develop.

![Screenshot_1](https://user-images.githubusercontent.com/58737803/210711278-4d5de1c0-3c41-430b-a23a-988d2f4907b4.png)

**Comment by ntminhdn** [comment]
@bedirhanayydin Thank you for your report. This is a bug. I have fixed it in [this PR](https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/pull/3).

**Comment by bedirhanayydin** [comment]
Thanks for your support.
