### ISSUE TITLE
UI rebuild when check has primarry focus

### ISSUE THREAD

**Issue by datnguyennt** [ntminhdn/Flutter-Bloc-CleanArchitecture#24]
https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/blob/e99cbeaf57ae017ea9b98987be4e0f9d02a68d9c/shared/lib/src/utils/view_utils.dart#L31C12-L31C12

**Comment by datnguyennt** [comment]
Hi, I have an issue when using your template, if I use this code 
```
     if (!currentFocus.hasPrimaryFocus && currentFocus.focusedChild != null) {
       FocusManager.instance.primaryFocus?.unfocus();
     }
```
The UI will rebuild when I tap inside and outside the text field. But if I only use 
`FocusManager.instance.primaryFocus?.unfocus();`
without if statement, the keyboard hide and UI not rebuild. Could you help me explain why? Thank you!
Note: You can add a debugPrint on top of BlocProvider and inside a BlocBuilder to see it rebuild many time

**Comment by mynavitechtus-minhnt3** [comment]
@datnguyennt I could not reproduce this bug on Flutter 3.10.5. Could you give me a sample code to reproduce the issue? And please provide me with the result of the command `flutter doctor`

**Comment by datnguyennt** [comment]
Hi @minhnt3 sorry for the late reply but I've fixed the issue. I have some questions about Bloc and Flutter, Can I have your contact?

**Comment by mynavitechtus-minhnt3** [comment]
@datnguyennt Yes, you can connect to [my LinkedIn account](https://www.linkedin.com/in/minh-nguyen-88412616b)
