### ISSUE TITLE
Problem with Generating the code

### ISSUE THREAD

**Issue by MurhafMoussa** [ntminhdn/Flutter-Bloc-CleanArchitecture#31]
Greetings
First of All, I want to thank you for the huge effort building this boilerplate.
I have a problem with installing .. after I activated melos , when I run "dart run tools/gen_env.dart" it gives me this message
"Could not find package `tools/gen_env.dart` or file `tools/gen_env.dart`"
Can you please check it out ? or if you have a discord .. can you help me with it ?

**Comment by mynavitechtus-minhnt3** [comment]
@MurhafMoussa you should run `dart run tools/gen_env/lib/main.dart` or `make gen_env`

**Comment by mynavitechtus-minhnt3** [comment]
@MurhafMoussa It seems like a mistake in my articles. I updated it. Thanks for reporting.

**Comment by MurhafMoussa** [comment]
@minhnt3  thanks it worked but there was another problems :
1- I had to run flutter pub get inside the tools\gen_env to get the xml dependency
2- I had an exception when I run the dart run tools/gen_env/lib/main.dart  which was this 
Error: The content of settings.json or launch.json is empty or the trailing comma is redundant or comments are invalid

        BAD:
        ```
        "settingA": {
          "keyA": "A",
          "keyB": "B", // <== Please remove this trailing comma
        }
        ```

        GOOD:
        ```
        "settingA": {
          "keyA": "A",
          "keyB": "B"
        }
        ```
        FormatException: Unexpected character (at line 10, character 17)
                // "--verbose",
                ^
So I went to the launcher.json and deleted all the comments related to verbose and it worked

**Comment by MurhafMoussa** [comment]
one more thing , I had this error when I run the make gen_env
make gen_env
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ make gen_env
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
I did't know how to fix it although I installed melos and configured all the environment variables 
ps: I am using Windows

**Comment by MurhafMoussa** [comment]
maybe this is because this configuration runs on mac .. I think you should make another configuration for Windows dont you think ?

**Comment by mynavitechtus-minhnt3** [comment]
@MurhafMoussa Yes. I will make it but for the time being, I could support for macOS. If you are using Windows, you could run the full command defined in the `makefile`. For example, `cd app && flutter pub run flutter_launcher_icons:main -f app_icon/app-icon.yaml` instead of `make update_app_icon`.

<img width="635" alt="image" src="https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/assets/93504649/36457c65-0374-4764-86c8-3ececfc3ca53">
