### ISSUE TITLE
failed build resources

### ISSUE THREAD

**Issue by MrRossi82** [ntminhdn/Flutter-Bloc-CleanArchitecture#34]
hello , 
when use make sync i have error 

**resources:
Failed to build intl_utils:generate:
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:1286:38: Error: Type 'ExtensionTypeDeclaration' not found.
  void visitExtensionTypeDeclaration(ExtensionTypeDeclaration node) {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:2630:43: Error: Type 'RepresentationConstructorName' not found.
  void visitRepresentationConstructorName(RepresentationConstructorName node) {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:2636:39: Error: Type 'RepresentationDeclaration' not found.
  void visitRepresentationDeclaration(RepresentationDeclaration node) {
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:1286:38: Error: 'ExtensionTypeDeclaration' isn't a type.
  void visitExtensionTypeDeclaration(ExtensionTypeDeclaration node) {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:2630:43: Error: 'RepresentationConstructorName' isn't a type.
  void visitRepresentationConstructorName(RepresentationConstructorName node) {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/source_visitor.dart:2636:39: Error: 'RepresentationDeclaration' isn't a type.

  void visitRepresentationDeclaration(RepresentationDeclaration node) {
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_style-2.3.4/lib/src/front_end/ast_node_visitor.dart:683:38: Error: Non-nullable variable 'forPartsPiece' must be assigned before it can be used.
    pieces.give(ForPiece(forKeyword, forPartsPiece, body,
                                     ^^^^^^^^^^^^^

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos exec
  └> flutter pub run intl_utils:generate
     └> FAILED (in 1 packages)
        └> resources (with exit code 1)

melos run l10n
  └> dart pub global run melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run intl_utils:generate
     └> FAILED
ScriptException: The script l10n failed to execute.
make: *** [sync] Error 1**

i try flutter 3.16.0
and 3.13.0

**Comment by wickyou23** [comment]
The same error with me.

**Comment by mynavitechtus-minhnt3** [comment]
I fixed it in [this PR](https://github.com/ntminhdn/Flutter-Bloc-CleanArchitecture/pull/35). Please check!
