### ISSUE TITLE
Bloc to bloc communication

### ISSUE THREAD

**Issue by saswattech9** [ntminhdn/Flutter-Bloc-CleanArchitecture#37]
With this architecture how to communicate between blocs .

Please someone explain with small example.

**Comment by saswattech9** [comment]
anyone can help me out ?

**Comment by hungtrn75** [comment]
I think u can use depend bloc as a param in constructor. i.e: bloc A depend on bloc B: A(B b) or u can create a global bloc

**Comment by saswattech9** [comment]
Global would not be a good option. So what you telling could you give us some example ?

**Comment by hungtrn75** [comment]
Ex: I have a A bloc depends on B, C bloc
```
ABloc extends BaseBloc<> {
  late final B bBloc;
  late final C cBloc;
}
```
u can overide in ur page
```
class _PageState extends BasePageState<Page, ABloc> {
  @override
  late final ABloc bloc = super.bloc
    ..bBloc = B()
    ..cBloc = C();
```
or init b,c instance in initState()
```
bloc
  ..bBloc = B()
  ..cBloc = C();
```
