### ISSUE TITLE
separation by feature

### ISSUE THREAD

**Issue by ALAZZURRI** [ntminhdn/Flutter-Bloc-CleanArchitecture#6]
Hello bro , I want ask u about  why don't Folder separation by feature on modules  like data , domain 
like this data module :

Account feature 
 -- DataSource  ( have 3 folders local | remote | Repository )
        -local --> DB For Account (save user info ...etc )
     - Remote --> Account Service (use  api)
        - Repository --> AccountRepositoryImpl 
     -

**Comment by ntminhdn** [comment]
@ALAZZURRI Thank you for your feedback. I think it depends on everyone's personal taste. Separating folders makes your code more clean and detailed. I will look into it.
